---
- name: install postgresql server
  yum:
    name: postgresql-server
    state: latest

- name: enable postgres at boot
  service:
    name: postgresql
    enabled: yes    

- name: Initilize postgres
  command: postgresql-setup initdb
  args:
    creates: /var/lib/pgsql/data/postgresql.conf
  notify: restart-postgres



# - name: tell user to finish setting up postgres
#   debug:
#     msg: "Either uncomment the postgres setup or manually login and initialize"

# only run the next 2 tasks once!
#  - name: initilize postgres
#    command: postgresql-setup initdb


# - name: start postgres
#   service:
#     name: postgresql.service
#     state: started