---
- name: install apache
  hosts: apps
  gather_facts: true
  become: true
  tasks:
    - block:
      - include_role: 
          name: enable-repos
      - include_role: 
          name: install-apache
